// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zadanie02.Database;

namespace Zadanie02.Migrations
{
    [DbContext(typeof(PismoContext))]
    [Migration("20201108230735_Inicialize")]
    partial class Inicialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Zadanie02.Database.Pismo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("CzySkasowany")
                        .HasColumnType("bit");

                    b.Property<string>("Nazwa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Priorytet")
                        .HasColumnType("bit");

                    b.Property<int>("Rocznik")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Pisma");

                    b.HasData(
                        new
                        {
                            Id = "p1",
                            CzySkasowany = false,
                            Nazwa = "Pismo 1",
                            Priorytet = false,
                            Rocznik = 2019
                        },
                        new
                        {
                            Id = "p2",
                            CzySkasowany = false,
                            Nazwa = "Pismo 2",
                            Priorytet = true,
                            Rocznik = 2019
                        },
                        new
                        {
                            Id = "p3",
                            CzySkasowany = true,
                            Nazwa = "Pismo 3",
                            Priorytet = true,
                            Rocznik = 2019
                        },
                        new
                        {
                            Id = "p4",
                            CzySkasowany = true,
                            Nazwa = "Pismo 4",
                            Priorytet = false,
                            Rocznik = 2019
                        },
                        new
                        {
                            Id = "p5",
                            CzySkasowany = false,
                            Nazwa = "Pismo 5",
                            Priorytet = false,
                            Rocznik = 2020
                        },
                        new
                        {
                            Id = "p6",
                            CzySkasowany = false,
                            Nazwa = "Pismo 6",
                            Priorytet = true,
                            Rocznik = 2020
                        },
                        new
                        {
                            Id = "p7",
                            CzySkasowany = true,
                            Nazwa = "Pismo 7",
                            Priorytet = true,
                            Rocznik = 2020
                        },
                        new
                        {
                            Id = "p8",
                            CzySkasowany = true,
                            Nazwa = "Pismo 8",
                            Priorytet = false,
                            Rocznik = 2020
                        },
                        new
                        {
                            Id = "p9",
                            CzySkasowany = false,
                            Nazwa = "Pismo 9",
                            Priorytet = false,
                            Rocznik = 2020
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
